apiVersion: v1
kind: Service
metadata:
  name: svc-py3
  labels:
    app: py3-conda
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8888
    protocol: TCP
    name: jupyter
  selector:
    app: py3-conda
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: py3-conda
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: py3-conda
    spec:
      containers:
      - name: py3-conda
        image: 202.116.46.215/hsdocker2019/python-conda-3:v1.0
        ports:
        - containerPort: 8888