apiVersion: v1
kind: Service
metadata:
  name: hadoop-dn-service
  labels:
    app: hadoop-dn
spec:
  ports:
    - port: 9000
      name: hdfs
    - port: 50010
      name: data-node-trans
    - port: 50075
      name: data-node-http
  clusterIP: None
  selector:
    app: hadoop-slave
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: slave
spec:
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: hadoop-slave
  serviceName: hadoop-dn-service
  template:
    metadata:
      labels:
        app: hadoop-slave
    spec:
      containers:
        - name: hadoop-slave
          image: 202.116.46.215/hsdocker2019/hs_hadoop:v1.0
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "1.7Gi"
              cpu: "1100m"
            limits:
              memory: "3.2Gi"
              cpu: "2500m"         
