apiVersion: v1
kind: Service
metadata:
  name: hadoop-nn-service
  labels:
    app: hadoop-nn
spec:
  ports:
    - port: 9000
      name: hdfs
    - port: 50070
      name: name-node
  clusterIP: None
  selector:
    app: hadoop-master
---
apiVersion: v1
kind: Pod
metadata:
  name: master
  labels:
    app: hadoop-master
spec:
  containers:
    - image: 202.116.46.215/hsdocker2019/hs_hadoop:v1.0
      name: hadoop-master
      imagePullPolicy: IfNotPresent
      resources:
        requests:
          memory: "0.5Gi"
          cpu: "800ms"
        limits:
          memory: "1.6Gi"
          cpu: "1800ms"           

