apiVersion: v1
kind: Service
metadata:
  name: hive-ui-service
spec:
  ports:
    - port: 8088
      name: resource-manager
    - port: 50070
      name: name-node
  selector:
    app: hive-master
  type: NodePort
