apiVersion: v1
kind: Pod
metadata:
  name: hadoop-master
  labels:
    app: hadoop-master
spec:
  containers:
    - name: hadoop-master
      image: 192.168.56.1:5000/chellyk-hadoop:latest
      imagePullPolicy: Never