##创建 NFS-pvc
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: hadoop-pvc
  namespace: test
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  selector:
    matchLabels:
      pv: nfs-pv
