##创建 hadoop-pvc
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: slavedata-slave-0
  namespace: test
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      pv: hadoop-pv
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: slavedata-slave-1
  namespace: test
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      pv: hadoop-pv

