apiVersion: v1
kind: Service
metadata:
  name: hadoop-nn-service
  labels:
    app: hadoop-nn
spec:
  ports:
    - port: 9000
      name: hdfs
    - port: 50070
      name: name-node
  clusterIP: None
  selector:
    app: hadoop-master
---
apiVersion: v1
kind: Pod
metadata:
  name: master
  labels:
    app: hadoop-master
spec:
  containers:
  - image: 202.116.46.215/hsdocker2019/hs_hadoop:v1.0
    name: hadoop-master
    imagePullPolicy: Always
    command: ["bash", "-c", "cp /etc/config/hadoop/profile /etc/profile && source /etc/profile && cp /etc/config/hadoop/* /usr/local/hadoop/etc/hadoop/ && rm /usr/local/hadoop/etc/hadoop/profile && service ssh start && trap : TERM INT; sleep infinity & wait"]
    volumeMounts:
    - name: hadoop-config
      mountPath: /etc/config/hadoop
  volumes:
    - name: hadoop-config
      configMap:
        name: hadoop-config
