apiVersion: v1
kind: Service
metadata:
  name: hive-slave-service
  labels:
    app: hive-slave
spec:
  ports:
    - port: 9000
      name: hdfs
    - port: 50010
      name: data-node-trans
    - port: 50075
      name: data-node-http
    - port: 2181
      name: zookeeper
  clusterIP: None
  selector:
    app: hive-slave
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: slave
spec:
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: hive-slave
  serviceName: hive-slave-service
  template:
    metadata:
      labels:
        app: hive-slave
    spec:
      containers:
        - name: hive-slave
          image: 202.116.46.215/hsdocker2019/hs_hive:v1.0
          imagePullPolicy: Always
