apiVersion: v1
kind: Service
metadata:
  name: mahout-ui-service
spec:
  ports:
    - port: 8088
      name: resource-manager
    - port: 50070
      name: name-node
  selector:
    app: mahout-master
  type: NodePort
