apiVersion: v1
kind: Service
metadata:
  name: hive-master-service
  labels:
    app: hive-master
spec:
  ports:
    - port: 9000
      name: hdfs
    - port: 50070
      name: name-node
    - port: 2181
      name: zookeeper
  clusterIP: None
  selector:
    app: hive-master
---
apiVersion: v1
kind: Pod
metadata:
  name: master
  labels:
    app: hive-master
spec:
  containers:
    - image: 192.168.56.1:5000/chellyk-hive:latest
      name: hive-master
      imagePullPolicy: Always
