apiVersion: v1
kind: Service
metadata:
  name: spark-ui-service
spec:
  ports:
    - port: 8088
      name: resource-manager
    - port: 50070
      name: name-node
    - port: 8080
      name: spark
  selector:
    app: spark-master
  type: NodePort
