apiVersion: v1
kind: Service
metadata:
  name: hadoop-dn-service
  labels:
    app: hadoop-dn
spec:
  ports:
    - port: 9000
      name: hdfs
    - port: 50010
      name: data-node-trans
    - port: 50075
      name: data-node-http
  clusterIP: None
  selector:
    app: hadoop-slave
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: slave
spec:
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: hadoop-slave
  serviceName: hadoop-dn-service
  template:
    metadata:
      labels:
        app: hadoop-slave
    spec:
      containers:
        - name: hadoop-slave
          image: 202.116.46.215/hsdocker2019/hs_hadoop:v1.0
          imagePullPolicy: Always
          resources:
            requests:
              memory: "1Gi"
              cpu: "0.5"
            limits:
              memory: "1Gi"
              cpu: "0.5"             
          command: 
          - bash
          - -c
          - "cp /etc/config/hadoop/profile /etc/profile && \
            source /etc/profile && \
            cp /etc/config/hadoop/* /usr/local/hadoop/etc/hadoop/ && \
            rm /usr/local/hadoop/etc/hadoop/profile && \
            service ssh start && \
            trap : TERM INT; sleep infinity & wait"   
          volumeMounts:
          - name: hadoop-config
            mountPath: /etc/config/hadoop
          - name: slavedata
            mountPath: /root/hdfs 
          env:
          - name: JAVA_TOOL_OPTIONS
            value: "-Dfile.encoding=UTF8"             
      volumes:
        - name: hadoop-config
          configMap:
            name: hadoop-config  
  volumeClaimTemplates:
  - metadata:
      name: slavedata
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
