##创建 master-pvc
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: master-pvc
  namespace: test
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  selector:
    matchLabels:
      pv: master-pv
