apiVersion: v1
kind: Service
metadata:
  name: kafka-master-service
  labels:
    app: kafka-master
spec:
  ports:
    - port: 2181
      name: zookeeper
  clusterIP: None
  selector:
    app: kafka-master
---
apiVersion: v1
kind: Pod
metadata:
  name: master
  labels:
    app: kafka-master
spec:
  containers:
    - image: 202.116.46.215/hsdocker2019/hs_kafka-zk:v1.0
      name: kafka-master
      imagePullPolicy: Always
      resources:
        requests:
          memory: "1Gi"
          cpu: "0.5"
        limits:
          memory: "1Gi"
          cpu: "0.5"          

