apiVersion: v1
kind: Service
metadata:
  name: hbase-slave-service
  labels:
    app: hbase-slave
spec:
  ports:
    - port: 9000
      name: hdfs
    - port: 50010
      name: data-node-trans
    - port: 50075
      name: data-node-http
    - port: 2181
      name: zookeeper
  clusterIP: None
  selector:
    app: hbase-slave
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: slave
spec:
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: hbase-slave
  serviceName: hbase-slave-service
  template:
    metadata:
      labels:
        app: hbase-slave
    spec:
      nodeName: node05
      containers:
        - name: hbase-slave
          image: 202.116.46.215/hsdocker2019/hs_hbase-zk-hadoop:v1.0 
          imagePullPolicy: Always
