apiVersion: v1
kind: Service
metadata:
  name: hbase-master-service
  labels:
    app: hbase-master
spec:
  ports:
    - port: 9000
      name: hdfs
    - port: 50070
      name: name-node
    - port: 2181
      name: zookeeper
  clusterIP: None
  selector:
    app: hbase-master
---
apiVersion: v1
kind: Pod
metadata:
  name: master
  labels:
    app: hbase-master
spec:
  containers:
    - image: 202.116.46.215/hsdocker2019/hbase-zk-hadoop:v1.0
      name: hbase-master
      imagePullPolicy: Always
