apiVersion: v1
kind: Service
metadata:
  name: hbase-ui-service
spec:
  ports:
    - port: 8088
      name: resource-manager
    - port: 50070
      name: name-node
    - port: 16010
      name: hbase
  selector:
    app: hbase-master
  type: NodePort
