apiVersion: v1
kind: Service
metadata:
  name: spark-master-service
  labels:
    app: spark-master
spec:
  ports:
    - port: 9000
      name: hdfs
    - port: 50070
      name: name-node
  clusterIP: None
  selector:
    app: spark-master
---
apiVersion: v1
kind: Pod
metadata:
  name: master
  labels:
    app: spark-master
spec:
  containers:
  - image: 202.116.46.215/hsdocker2019/hs_pig:v1.0
    name: spark-master
    imagePullPolicy: Always
    command: ["bash", "-c", "cp /etc/config/hadoop/profile /etc/profile && source /etc/profile && cp /etc/config/hadoop/* /usr/local/hadoop/etc/hadoop/ && rm /usr/local/hadoop/etc/hadoop/profile && service ssh start && trap : TERM INT; sleep infinity & wait"]
    volumeMounts:
    - name: hadoop-config
      mountPath: /etc/config/hadoop
    - name: hadoopm
      mountPath: /work  
    env:
    - name: JAVA_TOOL_OPTIONS
      value: "-Dfile.encoding=UTF8"
  volumes:
    - name: hadoop-config
      configMap:
        name: hadoop-config
    - name: hadoopm
      persistentVolumeClaim:
        claimName: hadoop-pvc    
