apiVersion: v1
kind: Service
metadata:
  name: plate-dection
  labels:
    app: plate-dection
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8888
    protocol: TCP
    name: jupyter
  selector:
    app: plate-dection
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: plate-dection
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: plate-dection
    spec:
      containers:
      - name: plate-dection
        image: 202.116.46.215/hsdocker2019/hs_plate-dection:py2_cpu-v1.0
        ports:
        - containerPort: 8888